USE university
SELECT COURSE.COURSE_ID, COUNT(*) AS 'AMOUNT'
FROM COURSE
INNER JOIN TAKES
ON TAKES.COURSE_ID = COURSE.COURSE_ID 
GROUP BY COURSE.COURSE_ID;

USE university
SELECT TAKES.ID AS 'STUDENT ID'
FROM TAKES
GROUP BY TAKES.ID
HAVING COUNT(TAKES.COURSE_ID) > 3;