USE CLASS1;
--1
SELECT *
FROM EMP E,
(SELECT AVG(SAL) AS 'AVG_SAL', DEPTNO FROM EMP GROUP BY DEPTNO) A_SAL
WHERE E.SAL > A_SAL.AVG_SAL
AND E.DEPTNO = A_SAL.DEPTNO;

--2
SELECT ENAME AS 'NAME', 
SAL - (SELECT AVG(D.SAL) FROM EMP D WHERE D.DEPTNO = E.DEPTNO GROUP BY D.DEPTNO) AS 'DIFF',
(SELECT COUNT(EMPNO) FROM EMP P WHERE E.DEPTNO = P.DEPTNO GROUP BY P.DEPTNO) AS 'COUNT'
FROM EMP E;


USE university;
--3
SELECT INSTRUCTOR.NAME, (CASE 
                         WHEN SALARY < 40000 THEN 'GRADE 1'
						 WHEN SALARY BETWEEN 40000 AND 60000 THEN 'GRADE 2'
						 WHEN SALARY BETWEEN 60000 AND 80000 THEN 'GRADE 3'
						 WHEN SALARY BETWEEN 80000 AND 100000 THEN 'GRADE 4'
						 ELSE 'GRADE 0'
						 END
						 ) AS 'GRADE'
FROM INSTRUCTOR;

--4/1
SELECT 
COUNT(CASE WHEN SALARY < 40000 THEN 'GRADE 1' END) AS 'GRADE 1',
COUNT(CASE WHEN SALARY BETWEEN 40000 AND 60000 THEN 'GRADE 2' END) AS 'GRADE 2',
COUNT(CASE WHEN SALARY BETWEEN 60000 AND 80000 THEN 'GRADE 3' END) AS 'GRADE 3',
COUNT(CASE WHEN SALARY BETWEEN 80000 AND 100000 THEN 'GRADE 4' END) AS 'GRADE 4',
COUNT(CASE WHEN SALARY > 100000 THEN 'GRADE 0' END) AS 'GRADE 0'
FROM INSTRUCTOR;

--4/2
WITH GRADE(T_NAME, SAL_GRADE) AS 
(SELECT INSTRUCTOR.NAME, (CASE 
                         WHEN SALARY < 40000 THEN 'GRADE 1'
						 WHEN SALARY BETWEEN 40000 AND 60000 THEN 'GRADE 2'
						 WHEN SALARY BETWEEN 60000 AND 80000 THEN 'GRADE 3'
						 WHEN SALARY BETWEEN 80000 AND 100000 THEN 'GRADE 4'
						 ELSE 'GRADE 0'
						 END
						 )
FROM INSTRUCTOR)
SELECT COUNT(*) AS 'COUNT' , SAL_GRADE
FROM GRADE
GROUP BY SAL_GRADE;