USE CLASS1

--1
SELECT ENAME, EMPNO, SAL
FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK');

--2
SELECT SUM(SAL)
FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE ENAME = 'Blake');

--3
SELECT * 
FROM EMP
WHERE DEPTNO NOT IN(SELECT DEPTNO FROM EMP WHERE ENAME = 'Blake')
INTERSECT 
SELECT * 
FROM EMP 
WHERE JOB IN(SELECT A.JOB FROM EMP A JOIN EMP B ON A.DEPTNO = B.DEPTNO AND B.ENAME = 'Blake');

--4
SELECT ENAME
 FROM EMP 
 WHERE SAL > SOME(SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO);

 --5.1
 SELECT DEPTNO, AVG(SAL)
 FROM EMP
 GROUP BY DEPTNO
 HAVING AVG(SAL) >= ALL(SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO);

 --5.2
 SELECT ENAME
 FROM EMP
 WHERE EMPNO IN(SELECT MGR FROM EMP);

 
 USE university;
--EXISTS SUB_QUERY
--1
SELECT STUDENT.ID, STUDENT.NAME, COUNT(TAKES.COURSE_ID)
FROM STUDENT
JOIN TAKES
ON STUDENT.ID = TAKES.ID
GROUP BY STUDENT.ID, STUDENT.NAME
HAVING COUNT(TAKES.COURSE_ID) > 2;

--2
SELECT NAME
FROM STUDENT S
WHERE NOT EXISTS(SELECT * FROM TAKES AS T WHERE S.ID = T.ID AND T.COURSE_ID = 'CS-347');

--3查询有员工的部门和部门号
USE CLASS1;
SELECT D.DNAME, D.DEPTNO
FROM DEPT D
WHERE EXISTS (SELECT * FROM EMP E WHERE D.DEPTNO = E.DEPTNO);

--4 FIND ALL STUDENTS WHO HAVE TAKEN ALL COURSES OFFERED IN THE BIOLOGY DEPARTMENT.
USE university;
SELECT DISTINCT S.ID, S.NAME
FROM STUDENT S
WHERE NOT EXISTS(SELECT C.COURSE_ID FROM COURSE C WHERE C.dept_name = 'Biology'
                 EXCEPT 
				 SELECT T.COURSE_ID FROM TAKES T
				 WHERE T.ID = S.ID);

--5
USE CLASS1;
SELECT D.DEPTNO
FROM EMP D
WHERE NOT EXISTS(SELECT DISTINCT A.JOB FROM EMP A WHERE MGR IS NOT NULL
                 EXCEPT
				 SELECT DISTINCT E.JOB FROM EMP E WHERE D.DEPTNO = E.DEPTNO);