--1
USE CLASS1;
SELECT EMP.DEPTNO, DEPT.DNAME, EMP.ENAME, SALGRADE.GRADE
FROM EMP 
JOIN DEPT 
ON EMP.DEPTNO = DEPT.DEPTNO
JOIN SALGRADE
ON EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL;

--2
USE university;
SELECT * 
FROM COURSE 
LEFT OUTER JOIN PREREQ
ON COURSE.COURSE_ID = PREREQ.COURSE_ID;