USE CLASS1;

SELECT * FROM BONUS;
SELECT * FROM DEPT;
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT COUNT(*) FROM EMP;

/*
3.	将所有员工的工资上浮10%.然后查询员工姓名、薪水、补助。（emp.sal为工资，emp.comm为补助）*/
UPDATE EMP SET SAL = SAL * 1.1;
SELECT ENAME AS 'NAME', SAL AS 'SALARY', COMM AS 'COMMISSION' FROM EMP;

UPDATE EMP SET SAL = SAL / 1.1;

/*
4.	查看EMP表中部门号为10的员工的姓名，职位，参加工作时间，工资。*/
SELECT ENAME AS 'NAME', JOB AS 'JOB', HIREDATE AS 'DATE', SAL AS 'SALARY' FROM EMP WHERE EMP.DEPTNO = 10;

/*
5.	查所有已有的职位，要求去除重复项。*/
SELECT DISTINCT JOB AS 'JOB' FROM EMP;

/*
6.	计算每个员工的年薪，并取列名为Salary of Year（emp.sal为员工的月薪），要求输出员工姓名，年薪。*/
SELECT ENAME AS 'NAME', SAL*12 AS 'Salary of Year' FROM EMP;

/*
7.	查询每个员工每个月拿到的总金额（emp.sal为工资，emp.comm为补助）。（提示：isnull（ex1,ex2）表示如果ex1为空则返回ex2）*/
SELECT ENAME AS 'NAME', SAL+ISNULL(COMM, 0) AS 'Salary' FROM EMP;

/*
8.	显示职位是主管（manager）的员工的姓名，工资。*/
SELECT ENAME AS 'NAME', SAL AS 'SALARY' FROM EMP WHERE JOB = 'MANAGER';

/*
9.	显示第3个字符为大写O的所有员工的姓名及工资。*/
SELECT ENAME AS 'NAME', SAL AS 'SALARY' FROM EMP WHERE ENAME LIKE '__O%';

/*
10.	显示职位为销售员（SALESMAN）或主管（MANAGER）的员工的姓名，工资，职位。*/
SELECT ENAME AS 'NAME', SAL AS 'SALARY', JOB AS 'JOB' FROM EMP WHERE JOB = 'SALESMAN' OR JOB = 'MANAGER';

/*
11.	显示所有没有补助的员工的姓名。*/
SELECT ENAME AS 'NAME' FROM EMP WHERE COMM IS NULL OR COMM = 0;

/*
12.	显示有补助的员工的姓名，工资，补助。*/
SELECT ENAME AS 'NAME', SAL AS 'SALARY', COMM AS 'COMMISSION' FROM EMP WHERE COMM IS NOT NULL AND COMM != 0;

/*
13.	排序显示所有员工的姓名，工资（按工资降序方式）*/
SELECT ENAME AS 'NAME', SAL AS 'SALARY' FROM EMP ORDER BY EMP.SAL DESC;

/*
14.	显示员工的最高工资和最低工资。*/
SELECT MAX(EMP.SAL) AS 'MAX SALARY', MIN(EMP.SAL) AS 'MIN SALARY' FROM EMP;

/*
15.	显示所有员工的平均工资和总计工资。*/
SELECT AVG(EMP.SAL) AS 'AVERAGE SALARY', SUM(EMP.SAL) AS 'SUMMERY SALARY' FROM EMP;

/*
16.	显示补助在员工中的发放比例、即有多少比例的员工有补助。
（此题需注意两个问题：1.select语句中进行除法如何保留小数点后数据。2.count函数如何处理null型数据。）*/
SELECT (COUNT(EMP.COMM)+0.0)/COUNT(*) FROM EMP;

/*(PROBLEM)
17.	显示每种职业的平均工资。*/
SELECT JOB, AVG(EMP.SAL) AS 'AVERAGE SALARY' FROM EMP GROUP BY JOB;

/*
18.	显示每个部门每种岗位的平均工资和最高工资。*/
SELECT DEPTNO,JOB, AVG(EMP.SAL) AS 'AVERAGE SALARY', MAX(EMP.SAL) AS 'MAX SALARY' FROM EMP GROUP BY DEPTNO, JOB;

/*
19.	显示平均工资低于2500的部门号，平均工资及最高工资。*/
SELECT DEPTNO, AVG(EMP.SAL) AS 'AVERAGE SALARY', MAX(EMP.SAL) AS 'MAX SALARY' FROM EMP
GROUP BY DEPTNO
HAVING AVG(EMP.SAL) <= 2500
ORDER BY AVG(EMP.SAL) ASC;

/*
20.	上一条语句以平均工资升序排序。
AT 19. */

/*
21.	显示工资高于2500或岗位为MANAGER的所有员工的姓名，工资，职位，和部门号。*/
SELECT ENAME, SAL, JOB, DEPTNO
FROM EMP
WHERE SAL > 2500 OR JOB = 'MANAGER';

/*
22.	排序显示所有员工的姓名，部门号，工资（以部门号升序，工资降序，雇用日期升序显示）。*/
SELECT ENAME, DEPTNO, SAL 
FROM EMP
ORDER BY DEPTNO ASC, SAL DESC, HIREDATE ASC;

/*
23.	采用自然连接原理显示部门名以及相应的员工姓名。（Sql server不支持NATURAL JOIN语法。）*/


/*
24.	查询SCOTT的上级领导的姓名。*/

/*
25.	显示部门的部门名称，员工名即使部门没有员工也显示部门名称。*/
USE CLASS1;
SELECT DEPT.DNAME, EMP.ENAME
FROM DEPT
LEFT OUTER JOIN EMP
ON DEPT.DEPTNO = EMP.DEPTNO;

/*
26.	显示所有员工的名称、工资以及工资级别。*/
SELECT EMP.ENAME, EMP.SAL, SALGRADE.GRADE
FROM EMP
JOIN SALGRADE
ON EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL;

/*
27.	显示ACCOUNTING部门所有员工的名称，工资。*/
SELECT EMP.ENAME, EMP.SAL
FROM EMP
JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DNAME = 'ACCOUNTING';

/*
28.	显示职位属于10号部门所提供职位范围的员工的姓名，职位，工资，部门号。*/
SELECT EMP.ENAME, EMP.JOB, EMP.SAL, EMP.DEPTNO
FROM EMP
WHERE EMP.JOB IN(SELECT EMP.JOB FROM EMP WHERE EMP.DEPTNO = 10);

/*
29.	显示在所有员工用中高于30号部门中任一个员工工资的员工的姓名，工资和部门号。*/
SELECT EMP.ENAME, EMP.SAL, EMP.DEPTNO
FROM EMP
WHERE EMP.SAL > ALL(SELECT EMP.SAL FROM EMP WHERE EMP.DEPTNO = 30);

/*
30.	显示工资高于2500或职位为MANAGER的员工的姓名，工资和职位（采用UNION语法实现）。*/
SELECT EMP.ENAME, EMP.SAL, EMP.JOB
FROM EMP
WHERE EMP.SAL > 2500
UNION
SELECT EMP.ENAME, EMP.SAL, EMP.JOB
FROM EMP
WHERE EMP.JOB = 'MANAGER';

/*
31.	显示工资高于2500且职位为MANAGER的员工的姓名，工资和职位（采用INTERSECT语法实现）。*/
SELECT EMP.ENAME, EMP.SAL, EMP.JOB
FROM EMP
WHERE EMP.SAL > 2500
INTERSECT
SELECT EMP.ENAME, EMP.SAL, EMP.JOB
FROM EMP
WHERE EMP.JOB = 'MANAGER';

/*
32.	显示工资高于2500但职位不是MANAGER的员工的姓名，工资和职位（采用EXCEPT语法实现）。*/
SELECT EMP.ENAME, EMP.SAL, EMP.JOB
FROM EMP
WHERE EMP.SAL > 2500
EXCEPT
SELECT EMP.ENAME, EMP.SAL, EMP.JOB
FROM EMP
WHERE EMP.JOB = 'MANAGER';