DELIMITER $
CREATE PROCEDURE ADMQ ()
BEGIN 
	INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) VALUES (210, "Chen", "Shi");
	UPDATE EMPLOYEES SET LAST_NAME = "Frank" WHERE EMPLOYEE_ID = 210;
	SELECT * FROM EMPLOYEES;
	DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 210;
END $
DELIMITER ;

CALL ADMQ();